### ISSUE TITLE
关于FLEN代码开源时间

### ISSUE THREAD

**Issue by Aliang-CN** [aimetrics/jarvis#1]
您好，FLEN代码计划什么时候开源呢？

**Comment by EthanYeoh** [comment]
您好，请问有计划开源代码吗？十分感谢

**Comment by aimetrics** [comment]
@linxingliang @EthanYeoh 抱歉，到现在还没开源。代码已经在TF2.0上实现，内部开源流程还是审核。最迟1月底开源。

**Comment by Aliang-CN** [comment]
好的，非常期待您的开源

**Comment by aimetrics** [comment]
> 好的，非常期待您的开源

代码提交了。有问题请反馈。这个issue可以closed了。

**Comment by Aliang-CN** [comment]
> > 好的，非常期待您的开源
> 
> 代码提交了。有问题请反馈。这个issue可以closed了。

你好，可以在makedown文档中增加论文题目或者链接吗，我突然忘记了是那篇论文。谢谢！

**Comment by aimetrics** [comment]
> > > 好的，非常期待您的开源
> > 
> > 
> > 代码提交了。有问题请反馈。这个issue可以closed了。
> 
> 你好，可以在makedown文档中增加论文题目或者链接吗，我突然忘记了是那篇论文。谢谢！

README更新了, 是这篇: https://arxiv.org/abs/1911.04690
