### ISSUE TITLE
No module named 'jarvis.core.globals'

### ISSUE THREAD

**Issue by liushuikong** [aimetrics/jarvis#3]
No module named 'jarvis.core.globals'

**Comment by liushuikong** [comment]
globals.py这个脚本怎么没有

**Comment by aimetrics** [comment]
> globals.py这个脚本怎么没有

谢谢你发现和issue!  问题修复了: https://github.com/aimetrics/jarvis/commit/25e18d0879dc48a7f14ded84138ab25ac8b6264a
