### ISSUE TITLE
field info

### ISSUE THREAD

**Issue by diwuxiaoxu** [aimetrics/jarvis#4]
请问，您对于Avazu数据集，field info的划分结果是什么样的？

**Comment by aimetrics** [comment]
3个field分别是这样的: @diwuxiaoxu 
DEVICE: hour, device_id, device_ip, device_model, device_type, device_conn_type
SITE-APP: site_id, site_domain, site_category, app_id, app_domain, app_category
BANNER: C1, banner_pos, C14-20

**Comment by diwuxiaoxu** [comment]
您好，感谢您的回信。按照您在FLEN模型中提出基于field层级关系的划分，那么每个属性列都应该具有具体的含义，请问您把C1，C14-C20，banner_pos划分在一个field的依据是什么？

**Comment by aimetrics** [comment]
> 您好，感谢您的回信。按照您在FLEN模型中提出基于field层级关系的划分，那么每个属性列都应该具有具体的含义，请问您把C1，C14-C20，banner_pos划分在一个field的依据是什么？

不大记得了。猜测这些字段的含义都是关于context的。有个kaggle比赛的方案介绍里说了。

**Comment by diwuxiaoxu** [comment]
感谢您的回信，问题已经解决
